services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master"
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"

  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    depends_on:
      - spark-master
    ports:
      - "8082:8081"

  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    depends_on:
      - spark-master
    ports:
      - "9999:9999"
    environment:
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_PORT=9999
      - SPARK_MASTER=spark://spark-master:7077
      - ZEPPELIN_SPARK_DEP_LOADER=zeppelin
      - ZEPPELIN_SPARK_USEHIVECONTEXT=false
    volumes:
      - ./notebooks:/zeppelin/notebook
